/*
 * InfluxDB OSS API Service
 *
 * The InfluxDB v2 API provides a programmatic interface for all interactions with InfluxDB. Access the InfluxDB API using the `/api/v2/` endpoint. 
 *
 * The version of the OpenAPI document: 2.0.0
 * Generated by: https://github.com/openapitools/openapi-generator.git
 */


using System;
using System.Collections;
using System.Collections.Generic;
using System.Collections.ObjectModel;
using System.Linq;
using System.IO;
using System.Runtime.Serialization;
using System.Text;
using System.Text.RegularExpressions;
using Newtonsoft.Json;
using Newtonsoft.Json.Converters;
using Newtonsoft.Json.Linq;
using FileParameter = InfluxDB.Client.Core.Api.FileParameter;
using OpenAPIDateConverter = InfluxDB.Client.Core.Api.OpenAPIDateConverter;

namespace InfluxDB.Client.Api.Domain
{
    /// <summary>
    /// BucketShardMapping
    /// </summary>
    [DataContract(Name = "BucketShardMapping")]
    public partial class BucketShardMapping : IEquatable<BucketShardMapping>
    {
        /// <summary>
        /// Initializes a new instance of the <see cref="BucketShardMapping" /> class.
        /// </summary>
        [JsonConstructorAttribute]
        protected BucketShardMapping() { }
        /// <summary>
        /// Initializes a new instance of the <see cref="BucketShardMapping" /> class.
        /// </summary>
        /// <param name="oldId">oldId (required).</param>
        /// <param name="newId">newId (required).</param>
        public BucketShardMapping(long oldId = default(long), long newId = default(long))
        {
            this.OldId = oldId;
            this.NewId = newId;
        }

        /// <summary>
        /// Gets or Sets OldId
        /// </summary>
        [DataMember(Name = "oldId", IsRequired = true, EmitDefaultValue = false)]
        public long OldId { get; set; }

        /// <summary>
        /// Gets or Sets NewId
        /// </summary>
        [DataMember(Name = "newId", IsRequired = true, EmitDefaultValue = false)]
        public long NewId { get; set; }

        /// <summary>
        /// Returns the string presentation of the object
        /// </summary>
        /// <returns>String presentation of the object</returns>
        public override string ToString()
        {
            var sb = new StringBuilder();
            sb.Append("class BucketShardMapping {\n");
            sb.Append("  OldId: ").Append(OldId).Append("\n");
            sb.Append("  NewId: ").Append(NewId).Append("\n");
            sb.Append("}\n");
            return sb.ToString();
        }

        /// <summary>
        /// Returns the JSON string presentation of the object
        /// </summary>
        /// <returns>JSON string presentation of the object</returns>
        public virtual string ToJson()
        {
            return Newtonsoft.Json.JsonConvert.SerializeObject(this, Newtonsoft.Json.Formatting.Indented);
        }

        /// <summary>
        /// Returns true if objects are equal
        /// </summary>
        /// <param name="input">Object to be compared</param>
        /// <returns>Boolean</returns>
        public override bool Equals(object input)
        {
            return this.Equals(input as BucketShardMapping);
        }

        /// <summary>
        /// Returns true if BucketShardMapping instances are equal
        /// </summary>
        /// <param name="input">Instance of BucketShardMapping to be compared</param>
        /// <returns>Boolean</returns>
        public bool Equals(BucketShardMapping input)
        {
            if (input == null)
                return false;

            return 
                (
                    this.OldId == input.OldId ||
                    this.OldId.Equals(input.OldId)
                ) && 
                (
                    this.NewId == input.NewId ||
                    this.NewId.Equals(input.NewId)
                );
        }

        /// <summary>
        /// Gets the hash code
        /// </summary>
        /// <returns>Hash code</returns>
        public override int GetHashCode()
        {
            unchecked // Overflow is fine, just wrap
            {
                int hashCode = 41;
                hashCode = hashCode * 59 + this.OldId.GetHashCode();
                hashCode = hashCode * 59 + this.NewId.GetHashCode();
                return hashCode;
            }
        }

    }

}
