/* 
 * InfluxDB OSS API Service
 *
 * The InfluxDB v2 API provides a programmatic interface for all interactions with InfluxDB. Access the InfluxDB API using the `/api/v2/` endpoint. 
 *
 * OpenAPI spec version: 2.0.0
 * 
 * Generated by: https://github.com/openapitools/openapi-generator.git
 */

using System;
using System.Linq;
using System.IO;
using System.Text;
using System.Text.RegularExpressions;
using System.Collections;
using System.Collections.Generic;
using System.Collections.ObjectModel;
using System.Runtime.Serialization;
using Newtonsoft.Json;
using Newtonsoft.Json.Converters;
using OpenAPIDateConverter = InfluxDB.Client.Api.Client.OpenAPIDateConverter;

namespace InfluxDB.Client.Api.Domain
{
    /// <summary>
    /// CellWithViewProperties
    /// </summary>
    [DataContract]
    public partial class CellWithViewProperties : Cell, IEquatable<CellWithViewProperties>
    {
        /// <summary>
        /// Initializes a new instance of the <see cref="CellWithViewProperties" /> class.
        /// </summary>
        /// <param name="name">name.</param>
        /// <param name="properties">properties.</param>
        public CellWithViewProperties(string name = default, ViewProperties properties = default, string id = default,
            CellLinks links = default, int? x = default, int? y = default, int? w = default, int? h = default,
            string viewID = default) : base(id, links, x, y, w, h, viewID)
        {
            Name = name;
            Properties = properties;
        }

        /// <summary>
        /// Gets or Sets Name
        /// </summary>
        [DataMember(Name = "name", EmitDefaultValue = false)]
        public string Name { get; set; }

        /// <summary>
        /// Gets or Sets Properties
        /// </summary>
        [DataMember(Name = "properties", EmitDefaultValue = false)]
        public ViewProperties Properties { get; set; }

        /// <summary>
        /// Returns the string presentation of the object
        /// </summary>
        /// <returns>String presentation of the object</returns>
        public override string ToString()
        {
            var sb = new StringBuilder();
            sb.Append("class CellWithViewProperties {\n");
            sb.Append("  ").Append(base.ToString().Replace("\n", "\n  ")).Append("\n");
            sb.Append("  Name: ").Append(Name).Append("\n");
            sb.Append("  Properties: ").Append(Properties).Append("\n");
            sb.Append("}\n");
            return sb.ToString();
        }

        /// <summary>
        /// Returns the JSON string presentation of the object
        /// </summary>
        /// <returns>JSON string presentation of the object</returns>
        public override string ToJson()
        {
            return JsonConvert.SerializeObject(this, Formatting.Indented);
        }

        /// <summary>
        /// Returns true if objects are equal
        /// </summary>
        /// <param name="input">Object to be compared</param>
        /// <returns>Boolean</returns>
        public override bool Equals(object input)
        {
            return Equals(input as CellWithViewProperties);
        }

        /// <summary>
        /// Returns true if CellWithViewProperties instances are equal
        /// </summary>
        /// <param name="input">Instance of CellWithViewProperties to be compared</param>
        /// <returns>Boolean</returns>
        public bool Equals(CellWithViewProperties input)
        {
            if (input == null)
            {
                return false;
            }

            return base.Equals(input) &&
                   (
                       Name == input.Name ||
                       Name != null && Name.Equals(input.Name)
                   ) && base.Equals(input) && Properties != null && Properties.Equals(input.Properties);
        }

        /// <summary>
        /// Gets the hash code
        /// </summary>
        /// <returns>Hash code</returns>
        public override int GetHashCode()
        {
            unchecked // Overflow is fine, just wrap
            {
                var hashCode = base.GetHashCode();

                if (Name != null)
                {
                    hashCode = hashCode * 59 + Name.GetHashCode();
                }

                if (Properties != null)
                {
                    hashCode = hashCode * 59 + Properties.GetHashCode();
                }

                return hashCode;
            }
        }
    }
}