/* 
 * InfluxDB OSS API Service
 *
 * The InfluxDB v2 API provides a programmatic interface for all interactions with InfluxDB. Access the InfluxDB API using the `/api/v2/` endpoint. 
 *
 * OpenAPI spec version: 2.0.0
 * 
 * Generated by: https://github.com/openapitools/openapi-generator.git
 */

using System;
using System.Linq;
using System.IO;
using System.Text;
using System.Text.RegularExpressions;
using System.Collections;
using System.Collections.Generic;
using System.Collections.ObjectModel;
using System.Runtime.Serialization;
using Newtonsoft.Json;
using Newtonsoft.Json.Converters;
using OpenAPIDateConverter = InfluxDB.Client.Api.Client.OpenAPIDateConverter;

namespace InfluxDB.Client.Api.Domain
{
    /// <summary>
    /// Error
    /// </summary>
    [DataContract]
    public partial class Error : IEquatable<Error>
    {
        /// <summary>
        /// code is the machine-readable error code.
        /// </summary>
        /// <value>code is the machine-readable error code.</value>
        [JsonConverter(typeof(StringEnumConverter))]
        public enum CodeEnum
        {
            /// <summary>
            /// Enum Internalerror for value: internal error
            /// </summary>
            [EnumMember(Value = "internal error")] Internalerror = 1,

            /// <summary>
            /// Enum Notfound for value: not found
            /// </summary>
            [EnumMember(Value = "not found")] Notfound = 2,

            /// <summary>
            /// Enum Conflict for value: conflict
            /// </summary>
            [EnumMember(Value = "conflict")] Conflict = 3,

            /// <summary>
            /// Enum Invalid for value: invalid
            /// </summary>
            [EnumMember(Value = "invalid")] Invalid = 4,

            /// <summary>
            /// Enum Unprocessableentity for value: unprocessable entity
            /// </summary>
            [EnumMember(Value = "unprocessable entity")]
            Unprocessableentity = 5,

            /// <summary>
            /// Enum Emptyvalue for value: empty value
            /// </summary>
            [EnumMember(Value = "empty value")] Emptyvalue = 6,

            /// <summary>
            /// Enum Unavailable for value: unavailable
            /// </summary>
            [EnumMember(Value = "unavailable")] Unavailable = 7,

            /// <summary>
            /// Enum Forbidden for value: forbidden
            /// </summary>
            [EnumMember(Value = "forbidden")] Forbidden = 8,

            /// <summary>
            /// Enum Toomanyrequests for value: too many requests
            /// </summary>
            [EnumMember(Value = "too many requests")]
            Toomanyrequests = 9,

            /// <summary>
            /// Enum Unauthorized for value: unauthorized
            /// </summary>
            [EnumMember(Value = "unauthorized")] Unauthorized = 10,

            /// <summary>
            /// Enum Methodnotallowed for value: method not allowed
            /// </summary>
            [EnumMember(Value = "method not allowed")]
            Methodnotallowed = 11,

            /// <summary>
            /// Enum Requesttoolarge for value: request too large
            /// </summary>
            [EnumMember(Value = "request too large")]
            Requesttoolarge = 12,

            /// <summary>
            /// Enum Unsupportedmediatype for value: unsupported media type
            /// </summary>
            [EnumMember(Value = "unsupported media type")]
            Unsupportedmediatype = 13
        }

        /// <summary>
        /// code is the machine-readable error code.
        /// </summary>
        /// <value>code is the machine-readable error code.</value>
        [DataMember(Name = "code", EmitDefaultValue = false)]
        public CodeEnum Code { get; set; }

        /// <summary>
        /// Initializes a new instance of the <see cref="Error" /> class.
        /// </summary>
        [JsonConstructorAttribute]
        public Error()
        {
        }


        /// <summary>
        /// Human-readable message.
        /// </summary>
        /// <value>Human-readable message.</value>
        [DataMember(Name = "message", EmitDefaultValue = false)]
        public string Message { get; private set; }

        /// <summary>
        /// Describes the logical code operation when the error occurred. Useful for debugging.
        /// </summary>
        /// <value>Describes the logical code operation when the error occurred. Useful for debugging.</value>
        [DataMember(Name = "op", EmitDefaultValue = false)]
        public string Op { get; private set; }

        /// <summary>
        /// Stack of errors that occurred during processing of the request. Useful for debugging.
        /// </summary>
        /// <value>Stack of errors that occurred during processing of the request. Useful for debugging.</value>
        [DataMember(Name = "err", EmitDefaultValue = false)]
        public string Err { get; private set; }

        /// <summary>
        /// Returns the string presentation of the object
        /// </summary>
        /// <returns>String presentation of the object</returns>
        public override string ToString()
        {
            var sb = new StringBuilder();
            sb.Append("class Error {\n");
            sb.Append("  Code: ").Append(Code).Append("\n");
            sb.Append("  Message: ").Append(Message).Append("\n");
            sb.Append("  Op: ").Append(Op).Append("\n");
            sb.Append("  Err: ").Append(Err).Append("\n");
            sb.Append("}\n");
            return sb.ToString();
        }

        /// <summary>
        /// Returns the JSON string presentation of the object
        /// </summary>
        /// <returns>JSON string presentation of the object</returns>
        public virtual string ToJson()
        {
            return JsonConvert.SerializeObject(this, Formatting.Indented);
        }

        /// <summary>
        /// Returns true if objects are equal
        /// </summary>
        /// <param name="input">Object to be compared</param>
        /// <returns>Boolean</returns>
        public override bool Equals(object input)
        {
            return Equals(input as Error);
        }

        /// <summary>
        /// Returns true if Error instances are equal
        /// </summary>
        /// <param name="input">Instance of Error to be compared</param>
        /// <returns>Boolean</returns>
        public bool Equals(Error input)
        {
            if (input == null)
            {
                return false;
            }

            return
                (
                    Code == input.Code ||
                    Code.Equals(input.Code)
                ) &&
                (
                    Message == input.Message ||
                    Message != null && Message.Equals(input.Message)
                ) &&
                (
                    Op == input.Op ||
                    Op != null && Op.Equals(input.Op)
                ) &&
                (
                    Err == input.Err ||
                    Err != null && Err.Equals(input.Err)
                );
        }

        /// <summary>
        /// Gets the hash code
        /// </summary>
        /// <returns>Hash code</returns>
        public override int GetHashCode()
        {
            unchecked // Overflow is fine, just wrap
            {
                var hashCode = 41;

                hashCode = hashCode * 59 + Code.GetHashCode();
                if (Message != null)
                {
                    hashCode = hashCode * 59 + Message.GetHashCode();
                }

                if (Op != null)
                {
                    hashCode = hashCode * 59 + Op.GetHashCode();
                }

                if (Err != null)
                {
                    hashCode = hashCode * 59 + Err.GetHashCode();
                }

                return hashCode;
            }
        }
    }
}