/* 
 * InfluxDB OSS API Service
 *
 * The InfluxDB v2 API provides a programmatic interface for all interactions with InfluxDB. Access the InfluxDB API using the `/api/v2/` endpoint. 
 *
 * OpenAPI spec version: 2.0.0
 * 
 * Generated by: https://github.com/openapitools/openapi-generator.git
 */

using System;
using System.Linq;
using System.IO;
using System.Text;
using System.Text.RegularExpressions;
using System.Collections;
using System.Collections.Generic;
using System.Collections.ObjectModel;
using System.Runtime.Serialization;
using Newtonsoft.Json;
using Newtonsoft.Json.Converters;
using OpenAPIDateConverter = InfluxDB.Client.Api.Client.OpenAPIDateConverter;

namespace InfluxDB.Client.Api.Domain
{
    /// <summary>
    /// HistogramViewProperties
    /// </summary>
    [DataContract]
    public partial class HistogramViewProperties : ViewProperties, IEquatable<HistogramViewProperties>
    {
        /// <summary>
        /// Defines Type
        /// </summary>
        [JsonConverter(typeof(StringEnumConverter))]
        public enum TypeEnum
        {
            /// <summary>
            /// Enum Histogram for value: histogram
            /// </summary>
            [EnumMember(Value = "histogram")] Histogram = 1
        }

        /// <summary>
        /// Gets or Sets Type
        /// </summary>
        [DataMember(Name = "type", EmitDefaultValue = false)]
        public TypeEnum Type { get; set; }

        /// <summary>
        /// Defines Shape
        /// </summary>
        [JsonConverter(typeof(StringEnumConverter))]
        public enum ShapeEnum
        {
            /// <summary>
            /// Enum ChronografV2 for value: chronograf-v2
            /// </summary>
            [EnumMember(Value = "chronograf-v2")] ChronografV2 = 1
        }

        /// <summary>
        /// Gets or Sets Shape
        /// </summary>
        [DataMember(Name = "shape", EmitDefaultValue = false)]
        public ShapeEnum Shape { get; set; }

        /// <summary>
        /// Defines Position
        /// </summary>
        [JsonConverter(typeof(StringEnumConverter))]
        public enum PositionEnum
        {
            /// <summary>
            /// Enum Overlaid for value: overlaid
            /// </summary>
            [EnumMember(Value = "overlaid")] Overlaid = 1,

            /// <summary>
            /// Enum Stacked for value: stacked
            /// </summary>
            [EnumMember(Value = "stacked")] Stacked = 2
        }

        /// <summary>
        /// Gets or Sets Position
        /// </summary>
        [DataMember(Name = "position", EmitDefaultValue = false)]
        public PositionEnum Position { get; set; }

        /// <summary>
        /// Initializes a new instance of the <see cref="HistogramViewProperties" /> class.
        /// </summary>
        [JsonConstructorAttribute]
        protected HistogramViewProperties()
        {
        }

        /// <summary>
        /// Initializes a new instance of the <see cref="HistogramViewProperties" /> class.
        /// </summary>
        /// <param name="type">type (required) (default to TypeEnum.Histogram).</param>
        /// <param name="queries">queries (required).</param>
        /// <param name="colors">Colors define color encoding of data into a visualization (required).</param>
        /// <param name="shape">shape (required) (default to ShapeEnum.ChronografV2).</param>
        /// <param name="note">note (required).</param>
        /// <param name="showNoteWhenEmpty">If true, will display note when empty (required).</param>
        /// <param name="xColumn">xColumn (required).</param>
        /// <param name="fillColumns">fillColumns (required).</param>
        /// <param name="xDomain">xDomain (required).</param>
        /// <param name="xAxisLabel">xAxisLabel (required).</param>
        /// <param name="position">position (required).</param>
        /// <param name="binCount">binCount (required).</param>
        /// <param name="legendColorizeRows">legendColorizeRows.</param>
        /// <param name="legendHide">legendHide.</param>
        /// <param name="legendOpacity">legendOpacity.</param>
        /// <param name="legendOrientationThreshold">legendOrientationThreshold.</param>
        public HistogramViewProperties(TypeEnum type = TypeEnum.Histogram, List<DashboardQuery> queries = default,
            List<DashboardColor> colors = default, ShapeEnum shape = ShapeEnum.ChronografV2, string note = default,
            bool? showNoteWhenEmpty = default, string xColumn = default, List<string> fillColumns = default,
            List<float?> xDomain = default, string xAxisLabel = default, PositionEnum position = default,
            int? binCount = default, bool? legendColorizeRows = default, bool? legendHide = default,
            float? legendOpacity = default, int? legendOrientationThreshold = default) : base()
        {
            // to ensure "type" is required (not null)
            Type = type;
            // to ensure "queries" is required (not null)
            if (queries == null)
            {
                throw new InvalidDataException(
                    "queries is a required property for HistogramViewProperties and cannot be null");
            }

            Queries = queries;
            // to ensure "colors" is required (not null)
            if (colors == null)
            {
                throw new InvalidDataException(
                    "colors is a required property for HistogramViewProperties and cannot be null");
            }

            Colors = colors;
            // to ensure "shape" is required (not null)
            Shape = shape;
            // to ensure "note" is required (not null)
            if (note == null)
            {
                throw new InvalidDataException(
                    "note is a required property for HistogramViewProperties and cannot be null");
            }

            Note = note;
            // to ensure "showNoteWhenEmpty" is required (not null)
            if (showNoteWhenEmpty == null)
            {
                throw new InvalidDataException(
                    "showNoteWhenEmpty is a required property for HistogramViewProperties and cannot be null");
            }

            ShowNoteWhenEmpty = showNoteWhenEmpty;
            // to ensure "xColumn" is required (not null)
            if (xColumn == null)
            {
                throw new InvalidDataException(
                    "xColumn is a required property for HistogramViewProperties and cannot be null");
            }

            XColumn = xColumn;
            // to ensure "fillColumns" is required (not null)
            if (fillColumns == null)
            {
                throw new InvalidDataException(
                    "fillColumns is a required property for HistogramViewProperties and cannot be null");
            }

            FillColumns = fillColumns;
            // to ensure "xDomain" is required (not null)
            if (xDomain == null)
            {
                throw new InvalidDataException(
                    "xDomain is a required property for HistogramViewProperties and cannot be null");
            }

            XDomain = xDomain;
            // to ensure "xAxisLabel" is required (not null)
            if (xAxisLabel == null)
            {
                throw new InvalidDataException(
                    "xAxisLabel is a required property for HistogramViewProperties and cannot be null");
            }

            XAxisLabel = xAxisLabel;
            // to ensure "position" is required (not null)
            Position = position;
            // to ensure "binCount" is required (not null)
            if (binCount == null)
            {
                throw new InvalidDataException(
                    "binCount is a required property for HistogramViewProperties and cannot be null");
            }

            BinCount = binCount;
            LegendColorizeRows = legendColorizeRows;
            LegendHide = legendHide;
            LegendOpacity = legendOpacity;
            LegendOrientationThreshold = legendOrientationThreshold;
        }


        /// <summary>
        /// Gets or Sets Queries
        /// </summary>
        [DataMember(Name = "queries", EmitDefaultValue = false)]
        public List<DashboardQuery> Queries { get; set; }

        /// <summary>
        /// Colors define color encoding of data into a visualization
        /// </summary>
        /// <value>Colors define color encoding of data into a visualization</value>
        [DataMember(Name = "colors", EmitDefaultValue = false)]
        public List<DashboardColor> Colors { get; set; }


        /// <summary>
        /// Gets or Sets Note
        /// </summary>
        [DataMember(Name = "note", EmitDefaultValue = false)]
        public string Note { get; set; }

        /// <summary>
        /// If true, will display note when empty
        /// </summary>
        /// <value>If true, will display note when empty</value>
        [DataMember(Name = "showNoteWhenEmpty", EmitDefaultValue = false)]
        public bool? ShowNoteWhenEmpty { get; set; }

        /// <summary>
        /// Gets or Sets XColumn
        /// </summary>
        [DataMember(Name = "xColumn", EmitDefaultValue = false)]
        public string XColumn { get; set; }

        /// <summary>
        /// Gets or Sets FillColumns
        /// </summary>
        [DataMember(Name = "fillColumns", EmitDefaultValue = false)]
        public List<string> FillColumns { get; set; }

        /// <summary>
        /// Gets or Sets XDomain
        /// </summary>
        [DataMember(Name = "xDomain", EmitDefaultValue = false)]
        public List<float?> XDomain { get; set; }

        /// <summary>
        /// Gets or Sets XAxisLabel
        /// </summary>
        [DataMember(Name = "xAxisLabel", EmitDefaultValue = false)]
        public string XAxisLabel { get; set; }


        /// <summary>
        /// Gets or Sets BinCount
        /// </summary>
        [DataMember(Name = "binCount", EmitDefaultValue = false)]
        public int? BinCount { get; set; }

        /// <summary>
        /// Gets or Sets LegendColorizeRows
        /// </summary>
        [DataMember(Name = "legendColorizeRows", EmitDefaultValue = false)]
        public bool? LegendColorizeRows { get; set; }

        /// <summary>
        /// Gets or Sets LegendHide
        /// </summary>
        [DataMember(Name = "legendHide", EmitDefaultValue = false)]
        public bool? LegendHide { get; set; }

        /// <summary>
        /// Gets or Sets LegendOpacity
        /// </summary>
        [DataMember(Name = "legendOpacity", EmitDefaultValue = false)]
        public float? LegendOpacity { get; set; }

        /// <summary>
        /// Gets or Sets LegendOrientationThreshold
        /// </summary>
        [DataMember(Name = "legendOrientationThreshold", EmitDefaultValue = false)]
        public int? LegendOrientationThreshold { get; set; }

        /// <summary>
        /// Returns the string presentation of the object
        /// </summary>
        /// <returns>String presentation of the object</returns>
        public override string ToString()
        {
            var sb = new StringBuilder();
            sb.Append("class HistogramViewProperties {\n");
            sb.Append("  ").Append(base.ToString().Replace("\n", "\n  ")).Append("\n");
            sb.Append("  Type: ").Append(Type).Append("\n");
            sb.Append("  Queries: ").Append(Queries).Append("\n");
            sb.Append("  Colors: ").Append(Colors).Append("\n");
            sb.Append("  Shape: ").Append(Shape).Append("\n");
            sb.Append("  Note: ").Append(Note).Append("\n");
            sb.Append("  ShowNoteWhenEmpty: ").Append(ShowNoteWhenEmpty).Append("\n");
            sb.Append("  XColumn: ").Append(XColumn).Append("\n");
            sb.Append("  FillColumns: ").Append(FillColumns).Append("\n");
            sb.Append("  XDomain: ").Append(XDomain).Append("\n");
            sb.Append("  XAxisLabel: ").Append(XAxisLabel).Append("\n");
            sb.Append("  Position: ").Append(Position).Append("\n");
            sb.Append("  BinCount: ").Append(BinCount).Append("\n");
            sb.Append("  LegendColorizeRows: ").Append(LegendColorizeRows).Append("\n");
            sb.Append("  LegendHide: ").Append(LegendHide).Append("\n");
            sb.Append("  LegendOpacity: ").Append(LegendOpacity).Append("\n");
            sb.Append("  LegendOrientationThreshold: ").Append(LegendOrientationThreshold).Append("\n");
            sb.Append("}\n");
            return sb.ToString();
        }

        /// <summary>
        /// Returns the JSON string presentation of the object
        /// </summary>
        /// <returns>JSON string presentation of the object</returns>
        public override string ToJson()
        {
            return JsonConvert.SerializeObject(this, Formatting.Indented);
        }

        /// <summary>
        /// Returns true if objects are equal
        /// </summary>
        /// <param name="input">Object to be compared</param>
        /// <returns>Boolean</returns>
        public override bool Equals(object input)
        {
            return Equals(input as HistogramViewProperties);
        }

        /// <summary>
        /// Returns true if HistogramViewProperties instances are equal
        /// </summary>
        /// <param name="input">Instance of HistogramViewProperties to be compared</param>
        /// <returns>Boolean</returns>
        public bool Equals(HistogramViewProperties input)
        {
            if (input == null)
            {
                return false;
            }

            return base.Equals(input) &&
                   (
                       Type == input.Type ||
                       Type.Equals(input.Type)
                   ) && base.Equals(input) &&
                   (
                       Queries == input.Queries ||
                       Queries != null &&
                       Queries.SequenceEqual(input.Queries)
                   ) && base.Equals(input) &&
                   (
                       Colors == input.Colors ||
                       Colors != null &&
                       Colors.SequenceEqual(input.Colors)
                   ) && base.Equals(input) &&
                   (
                       Shape == input.Shape ||
                       Shape.Equals(input.Shape)
                   ) && base.Equals(input) &&
                   (
                       Note == input.Note ||
                       Note != null && Note.Equals(input.Note)
                   ) && base.Equals(input) &&
                   (
                       ShowNoteWhenEmpty == input.ShowNoteWhenEmpty ||
                       ShowNoteWhenEmpty != null && ShowNoteWhenEmpty.Equals(input.ShowNoteWhenEmpty)
                   ) && base.Equals(input) &&
                   (
                       XColumn == input.XColumn ||
                       XColumn != null && XColumn.Equals(input.XColumn)
                   ) && base.Equals(input) &&
                   (
                       FillColumns == input.FillColumns ||
                       FillColumns != null &&
                       FillColumns.SequenceEqual(input.FillColumns)
                   ) && base.Equals(input) &&
                   (
                       XDomain == input.XDomain ||
                       XDomain != null &&
                       XDomain.SequenceEqual(input.XDomain)
                   ) && base.Equals(input) &&
                   (
                       XAxisLabel == input.XAxisLabel ||
                       XAxisLabel != null && XAxisLabel.Equals(input.XAxisLabel)
                   ) && base.Equals(input) &&
                   (
                       Position == input.Position ||
                       Position.Equals(input.Position)
                   ) && base.Equals(input) &&
                   (
                       BinCount == input.BinCount ||
                       BinCount != null && BinCount.Equals(input.BinCount)
                   ) && base.Equals(input) &&
                   (
                       LegendColorizeRows == input.LegendColorizeRows ||
                       LegendColorizeRows != null && LegendColorizeRows.Equals(input.LegendColorizeRows)
                   ) && base.Equals(input) &&
                   (
                       LegendHide == input.LegendHide ||
                       LegendHide != null && LegendHide.Equals(input.LegendHide)
                   ) && base.Equals(input) &&
                   (
                       LegendOpacity == input.LegendOpacity ||
                       LegendOpacity != null && LegendOpacity.Equals(input.LegendOpacity)
                   ) && base.Equals(input) &&
                   (
                       LegendOrientationThreshold == input.LegendOrientationThreshold ||
                       LegendOrientationThreshold != null &&
                       LegendOrientationThreshold.Equals(input.LegendOrientationThreshold)
                   );
        }

        /// <summary>
        /// Gets the hash code
        /// </summary>
        /// <returns>Hash code</returns>
        public override int GetHashCode()
        {
            unchecked // Overflow is fine, just wrap
            {
                var hashCode = base.GetHashCode();

                hashCode = hashCode * 59 + Type.GetHashCode();
                if (Queries != null)
                {
                    hashCode = hashCode * 59 + Queries.GetHashCode();
                }

                if (Colors != null)
                {
                    hashCode = hashCode * 59 + Colors.GetHashCode();
                }

                hashCode = hashCode * 59 + Shape.GetHashCode();
                if (Note != null)
                {
                    hashCode = hashCode * 59 + Note.GetHashCode();
                }

                if (ShowNoteWhenEmpty != null)
                {
                    hashCode = hashCode * 59 + ShowNoteWhenEmpty.GetHashCode();
                }

                if (XColumn != null)
                {
                    hashCode = hashCode * 59 + XColumn.GetHashCode();
                }

                if (FillColumns != null)
                {
                    hashCode = hashCode * 59 + FillColumns.GetHashCode();
                }

                if (XDomain != null)
                {
                    hashCode = hashCode * 59 + XDomain.GetHashCode();
                }

                if (XAxisLabel != null)
                {
                    hashCode = hashCode * 59 + XAxisLabel.GetHashCode();
                }

                hashCode = hashCode * 59 + Position.GetHashCode();
                if (BinCount != null)
                {
                    hashCode = hashCode * 59 + BinCount.GetHashCode();
                }

                if (LegendColorizeRows != null)
                {
                    hashCode = hashCode * 59 + LegendColorizeRows.GetHashCode();
                }

                if (LegendHide != null)
                {
                    hashCode = hashCode * 59 + LegendHide.GetHashCode();
                }

                if (LegendOpacity != null)
                {
                    hashCode = hashCode * 59 + LegendOpacity.GetHashCode();
                }

                if (LegendOrientationThreshold != null)
                {
                    hashCode = hashCode * 59 + LegendOrientationThreshold.GetHashCode();
                }

                return hashCode;
            }
        }
    }
}