/* 
 * InfluxDB OSS API Service
 *
 * The InfluxDB v2 API provides a programmatic interface for all interactions with InfluxDB. Access the InfluxDB API using the `/api/v2/` endpoint. 
 *
 * OpenAPI spec version: 2.0.0
 * 
 * Generated by: https://github.com/openapitools/openapi-generator.git
 */

using System;
using System.Linq;
using System.IO;
using System.Text;
using System.Text.RegularExpressions;
using System.Collections;
using System.Collections.Generic;
using System.Collections.ObjectModel;
using System.Runtime.Serialization;
using Newtonsoft.Json;
using Newtonsoft.Json.Converters;
using OpenAPIDateConverter = InfluxDB.Client.Api.Client.OpenAPIDateConverter;

namespace InfluxDB.Client.Api.Domain
{
    /// <summary>
    /// LogEvent
    /// </summary>
    [DataContract]
    public partial class LogEvent : IEquatable<LogEvent>
    {
        /// <summary>
        /// Initializes a new instance of the <see cref="LogEvent" /> class.
        /// </summary>
        [JsonConstructorAttribute]
        public LogEvent()
        {
        }

        /// <summary>
        /// Time event occurred, RFC3339Nano.
        /// </summary>
        /// <value>Time event occurred, RFC3339Nano.</value>
        [DataMember(Name = "time", EmitDefaultValue = false)]
        public DateTime? Time { get; private set; }

        /// <summary>
        /// A description of the event that occurred.
        /// </summary>
        /// <value>A description of the event that occurred.</value>
        [DataMember(Name = "message", EmitDefaultValue = false)]
        public string Message { get; private set; }

        /// <summary>
        /// the ID of the task that logged
        /// </summary>
        /// <value>the ID of the task that logged</value>
        [DataMember(Name = "runID", EmitDefaultValue = false)]
        public string RunID { get; private set; }

        /// <summary>
        /// Returns the string presentation of the object
        /// </summary>
        /// <returns>String presentation of the object</returns>
        public override string ToString()
        {
            var sb = new StringBuilder();
            sb.Append("class LogEvent {\n");
            sb.Append("  Time: ").Append(Time).Append("\n");
            sb.Append("  Message: ").Append(Message).Append("\n");
            sb.Append("  RunID: ").Append(RunID).Append("\n");
            sb.Append("}\n");
            return sb.ToString();
        }

        /// <summary>
        /// Returns the JSON string presentation of the object
        /// </summary>
        /// <returns>JSON string presentation of the object</returns>
        public virtual string ToJson()
        {
            return JsonConvert.SerializeObject(this, Formatting.Indented);
        }

        /// <summary>
        /// Returns true if objects are equal
        /// </summary>
        /// <param name="input">Object to be compared</param>
        /// <returns>Boolean</returns>
        public override bool Equals(object input)
        {
            return Equals(input as LogEvent);
        }

        /// <summary>
        /// Returns true if LogEvent instances are equal
        /// </summary>
        /// <param name="input">Instance of LogEvent to be compared</param>
        /// <returns>Boolean</returns>
        public bool Equals(LogEvent input)
        {
            if (input == null)
            {
                return false;
            }

            return
                (
                    Time == input.Time ||
                    Time != null && Time.Equals(input.Time)
                ) &&
                (
                    Message == input.Message ||
                    Message != null && Message.Equals(input.Message)
                ) &&
                (
                    RunID == input.RunID ||
                    RunID != null && RunID.Equals(input.RunID)
                );
        }

        /// <summary>
        /// Gets the hash code
        /// </summary>
        /// <returns>Hash code</returns>
        public override int GetHashCode()
        {
            unchecked // Overflow is fine, just wrap
            {
                var hashCode = 41;

                if (Time != null)
                {
                    hashCode = hashCode * 59 + Time.GetHashCode();
                }

                if (Message != null)
                {
                    hashCode = hashCode * 59 + Message.GetHashCode();
                }

                if (RunID != null)
                {
                    hashCode = hashCode * 59 + RunID.GetHashCode();
                }

                return hashCode;
            }
        }
    }
}