/* 
 * InfluxDB OSS API Service
 *
 * The InfluxDB v2 API provides a programmatic interface for all interactions with InfluxDB. Access the InfluxDB API using the `/api/v2/` endpoint. 
 *
 * OpenAPI spec version: 2.0.0
 * 
 * Generated by: https://github.com/openapitools/openapi-generator.git
 */

using System;
using System.Linq;
using System.IO;
using System.Text;
using System.Text.RegularExpressions;
using System.Collections;
using System.Collections.Generic;
using System.Collections.ObjectModel;
using System.Runtime.Serialization;
using Newtonsoft.Json;
using Newtonsoft.Json.Converters;
using OpenAPIDateConverter = InfluxDB.Client.Api.Client.OpenAPIDateConverter;

namespace InfluxDB.Client.Api.Domain
{
    /// <summary>
    /// QueryVariablePropertiesValues
    /// </summary>
    [DataContract]
    public partial class QueryVariablePropertiesValues : IEquatable<QueryVariablePropertiesValues>
    {
        /// <summary>
        /// Initializes a new instance of the <see cref="QueryVariablePropertiesValues" /> class.
        /// </summary>
        /// <param name="query">query.</param>
        /// <param name="language">language.</param>
        public QueryVariablePropertiesValues(string query = default, string language = default)
        {
            Query = query;
            Language = language;
        }

        /// <summary>
        /// Gets or Sets Query
        /// </summary>
        [DataMember(Name = "query", EmitDefaultValue = false)]
        public string Query { get; set; }

        /// <summary>
        /// Gets or Sets Language
        /// </summary>
        [DataMember(Name = "language", EmitDefaultValue = false)]
        public string Language { get; set; }

        /// <summary>
        /// Returns the string presentation of the object
        /// </summary>
        /// <returns>String presentation of the object</returns>
        public override string ToString()
        {
            var sb = new StringBuilder();
            sb.Append("class QueryVariablePropertiesValues {\n");
            sb.Append("  Query: ").Append(Query).Append("\n");
            sb.Append("  Language: ").Append(Language).Append("\n");
            sb.Append("}\n");
            return sb.ToString();
        }

        /// <summary>
        /// Returns the JSON string presentation of the object
        /// </summary>
        /// <returns>JSON string presentation of the object</returns>
        public virtual string ToJson()
        {
            return JsonConvert.SerializeObject(this, Formatting.Indented);
        }

        /// <summary>
        /// Returns true if objects are equal
        /// </summary>
        /// <param name="input">Object to be compared</param>
        /// <returns>Boolean</returns>
        public override bool Equals(object input)
        {
            return Equals(input as QueryVariablePropertiesValues);
        }

        /// <summary>
        /// Returns true if QueryVariablePropertiesValues instances are equal
        /// </summary>
        /// <param name="input">Instance of QueryVariablePropertiesValues to be compared</param>
        /// <returns>Boolean</returns>
        public bool Equals(QueryVariablePropertiesValues input)
        {
            if (input == null)
            {
                return false;
            }

            return
                (
                    Query == input.Query ||
                    Query != null && Query.Equals(input.Query)
                ) &&
                (
                    Language == input.Language ||
                    Language != null && Language.Equals(input.Language)
                );
        }

        /// <summary>
        /// Gets the hash code
        /// </summary>
        /// <returns>Hash code</returns>
        public override int GetHashCode()
        {
            unchecked // Overflow is fine, just wrap
            {
                var hashCode = 41;

                if (Query != null)
                {
                    hashCode = hashCode * 59 + Query.GetHashCode();
                }

                if (Language != null)
                {
                    hashCode = hashCode * 59 + Language.GetHashCode();
                }

                return hashCode;
            }
        }
    }
}