/* 
 * InfluxDB OSS API Service
 *
 * The InfluxDB v2 API provides a programmatic interface for all interactions with InfluxDB. Access the InfluxDB API using the `/api/v2/` endpoint. 
 *
 * OpenAPI spec version: 2.0.0
 * 
 * Generated by: https://github.com/openapitools/openapi-generator.git
 */

using System;
using System.Linq;
using System.IO;
using System.Text;
using System.Text.RegularExpressions;
using System.Collections;
using System.Collections.Generic;
using System.Collections.ObjectModel;
using System.Runtime.Serialization;
using Newtonsoft.Json;
using Newtonsoft.Json.Converters;
using OpenAPIDateConverter = InfluxDB.Client.Api.Client.OpenAPIDateConverter;

namespace InfluxDB.Client.Api.Domain
{
    /// <summary>
    /// SlackNotificationRule
    /// </summary>
    [DataContract]
    public partial class SlackNotificationRule : SlackNotificationRuleBase, IEquatable<SlackNotificationRule>
    {
        /// <summary>
        /// Initializes a new instance of the <see cref="SlackNotificationRule" /> class.
        /// </summary>
        [JsonConstructorAttribute]
        protected SlackNotificationRule()
        {
        }

        /// <summary>
        /// Initializes a new instance of the <see cref="SlackNotificationRule" /> class.
        /// </summary>
        public SlackNotificationRule(string endpointID = default, string orgID = default, string taskID = default,
            TaskStatusType status = default, string name = default, string sleepUntil = default, string every = default,
            string offset = default, string runbookLink = default, int? limitEvery = default, int? limit = default,
            List<TagRule> tagRules = default, string description = default, List<StatusRule> statusRules = default,
            List<Label> labels = default, NotificationRuleBaseLinks links = default, TypeEnum type = TypeEnum.Slack,
            string channel = default, string messageTemplate = default) : base(type, channel, messageTemplate,
            endpointID, orgID, taskID, status, name, sleepUntil, every, offset, runbookLink, limitEvery, limit,
            tagRules, description, statusRules, labels, links)
        {
        }

        /// <summary>
        /// Returns the string presentation of the object
        /// </summary>
        /// <returns>String presentation of the object</returns>
        public override string ToString()
        {
            var sb = new StringBuilder();
            sb.Append("class SlackNotificationRule {\n");
            sb.Append("  ").Append(base.ToString().Replace("\n", "\n  ")).Append("\n");
            sb.Append("}\n");
            return sb.ToString();
        }

        /// <summary>
        /// Returns the JSON string presentation of the object
        /// </summary>
        /// <returns>JSON string presentation of the object</returns>
        public override string ToJson()
        {
            return JsonConvert.SerializeObject(this, Formatting.Indented);
        }

        /// <summary>
        /// Returns true if objects are equal
        /// </summary>
        /// <param name="input">Object to be compared</param>
        /// <returns>Boolean</returns>
        public override bool Equals(object input)
        {
            return Equals(input as SlackNotificationRule);
        }

        /// <summary>
        /// Returns true if SlackNotificationRule instances are equal
        /// </summary>
        /// <param name="input">Instance of SlackNotificationRule to be compared</param>
        /// <returns>Boolean</returns>
        public bool Equals(SlackNotificationRule input)
        {
            if (input == null)
            {
                return false;
            }

            return base.Equals(input);
        }

        /// <summary>
        /// Gets the hash code
        /// </summary>
        /// <returns>Hash code</returns>
        public override int GetHashCode()
        {
            unchecked // Overflow is fine, just wrap
            {
                var hashCode = base.GetHashCode();

                return hashCode;
            }
        }
    }
}