/* 
 * InfluxDB OSS API Service
 *
 * The InfluxDB v2 API provides a programmatic interface for all interactions with InfluxDB. Access the InfluxDB API using the `/api/v2/` endpoint. 
 *
 * OpenAPI spec version: 2.0.0
 * 
 * Generated by: https://github.com/openapitools/openapi-generator.git
 */

using System;
using System.Linq;
using System.IO;
using System.Text;
using System.Text.RegularExpressions;
using System.Collections;
using System.Collections.Generic;
using System.Collections.ObjectModel;
using System.Runtime.Serialization;
using Newtonsoft.Json;
using Newtonsoft.Json.Converters;
using OpenAPIDateConverter = InfluxDB.Client.Api.Client.OpenAPIDateConverter;

namespace InfluxDB.Client.Api.Domain
{
    /// <summary>
    /// TemplateExportByIDOrgIDs
    /// </summary>
    [DataContract]
    public partial class TemplateExportByIDOrgIDs : IEquatable<TemplateExportByIDOrgIDs>
    {
        /// <summary>
        /// Initializes a new instance of the <see cref="TemplateExportByIDOrgIDs" /> class.
        /// </summary>
        /// <param name="orgID">orgID.</param>
        /// <param name="resourceFilters">resourceFilters.</param>
        public TemplateExportByIDOrgIDs(string orgID = default,
            TemplateExportByIDResourceFilters resourceFilters = default)
        {
            OrgID = orgID;
            ResourceFilters = resourceFilters;
        }

        /// <summary>
        /// Gets or Sets OrgID
        /// </summary>
        [DataMember(Name = "orgID", EmitDefaultValue = false)]
        public string OrgID { get; set; }

        /// <summary>
        /// Gets or Sets ResourceFilters
        /// </summary>
        [DataMember(Name = "resourceFilters", EmitDefaultValue = false)]
        public TemplateExportByIDResourceFilters ResourceFilters { get; set; }

        /// <summary>
        /// Returns the string presentation of the object
        /// </summary>
        /// <returns>String presentation of the object</returns>
        public override string ToString()
        {
            var sb = new StringBuilder();
            sb.Append("class TemplateExportByIDOrgIDs {\n");
            sb.Append("  OrgID: ").Append(OrgID).Append("\n");
            sb.Append("  ResourceFilters: ").Append(ResourceFilters).Append("\n");
            sb.Append("}\n");
            return sb.ToString();
        }

        /// <summary>
        /// Returns the JSON string presentation of the object
        /// </summary>
        /// <returns>JSON string presentation of the object</returns>
        public virtual string ToJson()
        {
            return JsonConvert.SerializeObject(this, Formatting.Indented);
        }

        /// <summary>
        /// Returns true if objects are equal
        /// </summary>
        /// <param name="input">Object to be compared</param>
        /// <returns>Boolean</returns>
        public override bool Equals(object input)
        {
            return Equals(input as TemplateExportByIDOrgIDs);
        }

        /// <summary>
        /// Returns true if TemplateExportByIDOrgIDs instances are equal
        /// </summary>
        /// <param name="input">Instance of TemplateExportByIDOrgIDs to be compared</param>
        /// <returns>Boolean</returns>
        public bool Equals(TemplateExportByIDOrgIDs input)
        {
            if (input == null)
            {
                return false;
            }

            return
            (
                OrgID == input.OrgID ||
                OrgID != null && OrgID.Equals(input.OrgID)
            ) && ResourceFilters != null && ResourceFilters.Equals(input.ResourceFilters);
        }

        /// <summary>
        /// Gets the hash code
        /// </summary>
        /// <returns>Hash code</returns>
        public override int GetHashCode()
        {
            unchecked // Overflow is fine, just wrap
            {
                var hashCode = 41;

                if (OrgID != null)
                {
                    hashCode = hashCode * 59 + OrgID.GetHashCode();
                }

                if (ResourceFilters != null)
                {
                    hashCode = hashCode * 59 + ResourceFilters.GetHashCode();
                }

                return hashCode;
            }
        }
    }
}