/* 
 * InfluxDB OSS API Service
 *
 * The InfluxDB v2 API provides a programmatic interface for all interactions with InfluxDB. Access the InfluxDB API using the `/api/v2/` endpoint. 
 *
 * OpenAPI spec version: 2.0.0
 * 
 * Generated by: https://github.com/openapitools/openapi-generator.git
 */

using System;
using System.Linq;
using System.IO;
using System.Text;
using System.Text.RegularExpressions;
using System.Collections;
using System.Collections.Generic;
using System.Collections.ObjectModel;
using System.Runtime.Serialization;
using Newtonsoft.Json;
using Newtonsoft.Json.Converters;
using OpenAPIDateConverter = InfluxDB.Client.Api.Client.OpenAPIDateConverter;

namespace InfluxDB.Client.Api.Domain
{
    /// <summary>
    /// TemplateExportByIDResourceFilters
    /// </summary>
    [DataContract]
    public partial class TemplateExportByIDResourceFilters : IEquatable<TemplateExportByIDResourceFilters>
    {
        /// <summary>
        /// Initializes a new instance of the <see cref="TemplateExportByIDResourceFilters" /> class.
        /// </summary>
        /// <param name="byLabel">byLabel.</param>
        /// <param name="byResourceKind">byResourceKind.</param>
        public TemplateExportByIDResourceFilters(List<string> byLabel = default,
            List<TemplateKind> byResourceKind = default)
        {
            ByLabel = byLabel;
            ByResourceKind = byResourceKind;
        }

        /// <summary>
        /// Gets or Sets ByLabel
        /// </summary>
        [DataMember(Name = "byLabel", EmitDefaultValue = false)]
        public List<string> ByLabel { get; set; }

        /// <summary>
        /// Gets or Sets ByResourceKind
        /// </summary>
        [DataMember(Name = "byResourceKind", EmitDefaultValue = false)]
        public List<TemplateKind> ByResourceKind { get; set; }

        /// <summary>
        /// Returns the string presentation of the object
        /// </summary>
        /// <returns>String presentation of the object</returns>
        public override string ToString()
        {
            var sb = new StringBuilder();
            sb.Append("class TemplateExportByIDResourceFilters {\n");
            sb.Append("  ByLabel: ").Append(ByLabel).Append("\n");
            sb.Append("  ByResourceKind: ").Append(ByResourceKind).Append("\n");
            sb.Append("}\n");
            return sb.ToString();
        }

        /// <summary>
        /// Returns the JSON string presentation of the object
        /// </summary>
        /// <returns>JSON string presentation of the object</returns>
        public virtual string ToJson()
        {
            return JsonConvert.SerializeObject(this, Formatting.Indented);
        }

        /// <summary>
        /// Returns true if objects are equal
        /// </summary>
        /// <param name="input">Object to be compared</param>
        /// <returns>Boolean</returns>
        public override bool Equals(object input)
        {
            return Equals(input as TemplateExportByIDResourceFilters);
        }

        /// <summary>
        /// Returns true if TemplateExportByIDResourceFilters instances are equal
        /// </summary>
        /// <param name="input">Instance of TemplateExportByIDResourceFilters to be compared</param>
        /// <returns>Boolean</returns>
        public bool Equals(TemplateExportByIDResourceFilters input)
        {
            if (input == null)
            {
                return false;
            }

            return
                (
                    ByLabel == input.ByLabel ||
                    ByLabel != null &&
                    ByLabel.SequenceEqual(input.ByLabel)
                ) &&
                (
                    ByResourceKind == input.ByResourceKind ||
                    ByResourceKind != null &&
                    ByResourceKind.SequenceEqual(input.ByResourceKind)
                );
        }

        /// <summary>
        /// Gets the hash code
        /// </summary>
        /// <returns>Hash code</returns>
        public override int GetHashCode()
        {
            unchecked // Overflow is fine, just wrap
            {
                var hashCode = 41;

                if (ByLabel != null)
                {
                    hashCode = hashCode * 59 + ByLabel.GetHashCode();
                }

                if (ByResourceKind != null)
                {
                    hashCode = hashCode * 59 + ByResourceKind.GetHashCode();
                }

                return hashCode;
            }
        }
    }
}